version: '3.4'

services:
  readmeter:
    image: readmeter
    build:
      context: .
      dockerfile: Readmeter/Dockerfile
    environment:
     - interval=20000
     - mqttIP=192.168.1.11
     - meterIP=192.168.1.10
